In [1]:
import os
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
REPORTS_DIR = "/s/ls4/users/grartem/RL_robots/CommandClassifier/models/"

In [13]:
table = []
for experimentName in ["rubert_tiny_multilabel", "rubert_tiny2_multilabel", "rubert_tiny2_multilabel_useY",
                       "MyMultiTiny2", "rubert_tiny2_labelflag"]:
    table.append({
            "experiment": experimentName,
        })
    for fold_i in range(5):
        if not os.path.exists(os.path.join(REPORTS_DIR, experimentName, "fold_{}".format(fold_i), "reports", "epoch-{}_avg_report.json".format(10))):
            continue
        with open(os.path.join(REPORTS_DIR, experimentName, "fold_{}".format(fold_i), "reports", "epoch-{}_avg_report.json".format(10)), "r") as f:
            report = json.load(f)
        table[-1]["fold_{}".format(fold_i)] = np.round(100*report['correct_samples_perc'], 2)
table_df = pd.DataFrame(table)
table_df

                     experiment  fold_0  fold_1  fold_2  fold_3  fold_4
0        rubert_tiny_multilabel   32.58   43.94   48.86   28.52   30.42
1       rubert_tiny2_multilabel   77.65   68.94   79.92   67.68   47.53
2  rubert_tiny2_multilabel_useY   85.23   93.56   89.77   84.03   79.85
3                  MyMultiTiny2   82.95   92.05   88.64   85.17   78.33
4        rubert_tiny2_labelflag   93.56   96.59   96.21   97.34   93.54

In [14]:
# Если не смотреть на У при подсчёте правильно предсказанных кортежей лейблов
for experimentName in ["rubert_tiny2_multilabel"]:
    table.append({
            "experiment": experimentName+"_noY",
        })
    for fold_i in range(5):
        if not os.path.exists(os.path.join(REPORTS_DIR, experimentName, "fold_{}".format(fold_i), "reports", "epoch-{}_avg_report.json".format(10))):
            continue
        with open(os.path.join(REPORTS_DIR, experimentName, "fold_{}".format(fold_i), "reports", "epoch-{}_avg_report_noY.json".format(10)), "r") as f:
            report = json.load(f)
        table[-1]["fold_{}".format(fold_i)] = np.round(100*report['correct_samples_perc'], 2)
table_df = pd.DataFrame(table)
table_df

                     experiment  fold_0  fold_1  fold_2  fold_3  fold_4
0        rubert_tiny_multilabel   32.58   43.94   48.86   28.52   30.42
1       rubert_tiny2_multilabel   77.65   68.94   79.92   67.68   47.53
2  rubert_tiny2_multilabel_useY   85.23   93.56   89.77   84.03   79.85
3                  MyMultiTiny2   82.95   92.05   88.64   85.17   78.33
4        rubert_tiny2_labelflag   93.56   96.59   96.21   97.34   93.54
5   rubert_tiny2_multilabel_noY   78.41   68.94   79.92   67.68   49.43

In [7]:
# Using Rule to exclude impossible combinations and chose most probable variants
table = []
for experimentName in ["rubert_tiny2_multilabel"]:
    table.append({
            "experiment": experimentName,
        })
    for fold_i in range(5):
        if not os.path.exists(os.path.join(REPORTS_DIR, experimentName, "fold_{}".format(fold_i), "reports", "epoch-{}_avg_report_rule.json".format(10))):
            continue
        with open(os.path.join(REPORTS_DIR, experimentName, "fold_{}".format(fold_i), "reports", "epoch-{}_avg_report_rule.json".format(10)), "r") as f:
            report = json.load(f)
        table[-1]["fold_{}".format(fold_i)] = np.round(100*report['correct_samples_perc'], 2)
table_df = pd.DataFrame(table)
table_df

                experiment  fold_0  fold_1  fold_2  fold_3  fold_4
0  rubert_tiny2_multilabel   79.17   70.08   80.68   68.44   48.67